name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Tools
        uses: jdx/mise-action@v2
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: mise tasks run format

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Tools
        uses: jdx/mise-action@v2
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Install clippy
        run: rustup component add clippy
      - name: Check linting
        run: mise tasks run lint

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Tools
        uses: jdx/mise-action@v2
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Build
        run: mise tasks run build

  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Tools
        uses: jdx/mise-action@v2
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Test
        run: mise tasks run test

  machete:
    name: Machete
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Tools
        uses: jdx/mise-action@v2
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Install machete
        run: cargo install cargo-machete
      - name: Run machete
        run: cargo machete
